[tool.poetry]
name = "gandalf"
version = "0.1.0"
description = "MusicXML Evaluation Tool"
authors = ["Your Name <you@example.com>"]
license = "GPL-3.0"

[tool.poetry.dependencies]
python = "^3.7"
attrs = "^19.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
